# Supplement Notebook for Project 3

In [1]:
import praw
import pandas as pd

In [2]:
reddit = praw.Reddit(client_id='OwVEAMEXqPhw8Q',
                        client_secret="cTb-60WClfOM_kZAMFD2hg6N_IY", password='dsi16-2020',
                        user_agent='Alexis 1.0', username='OkReddit1620')

In [17]:
sreddit_lpt = reddit.subreddit('LifeProTips')
lpt_hot_1000 = sreddit_lpt.top('year',limit=1000)

In [6]:
type(lpt_hot_1000)

praw.models.listing.generator.ListingGenerator

In [18]:
post_list = []
for p in lpt_hot_1000:
    post={}
    post['subreddit'] = str(p.subreddit)
    post['selftext'] = str(p.selftext)
    post['score'] = p.score
    post['title'] = str(p.title)
    post['upvote_ratio'] = p.upvote_ratio
    post['created_utc'] = p.created_utc
    post['id'] = str(p.id)
    post['fullname'] = str(p.fullname)
    post['num_comments'] = p.num_comments
    post['url'] = str(p.url)
    post['total_awards_received'] = p.total_awards_received
    post['author'] = p.author
    post_list.append(post)

In [19]:
len(post_list)

1000

In [20]:
df = pd.DataFrame(post_list)

In [21]:
df.head()

subreddit                                           selftext   score  \
0  LifeProTips  I had a phone interview scheduled this morning...  165153   
1  LifeProTips                                                     131334   
2  LifeProTips  I just found this quote online and wanted to s...  107877   
3  LifeProTips  Side note: this does not apply to people who a...  106215   
4  LifeProTips  The post nut clarity is real, without the humi...  104542   

                                               title  upvote_ratio  \
0  LPT: keep your mouth shut, and don't volunteer...          0.96   
1  LPT: If you want a smarter kid, teach your chi...          0.92   
2  LPT: Just because you did something wrong in t...          0.94   
3  LPT: The next time you catch yourself judging ...          0.92   
4  LPT: Anytime you think about contacting an ex ...          0.87   

    created_utc      id   fullname  num_comments  \
0  1.582156e+09  f6jt5e  t3_f6jt5e          4973   
1  1.585245e+09  fpfwra  t3_fpfwra          3103   
2  1.588878e+09  gfcq4g  t3_gfcq4g          2036   
3  1.593094e+09  hfmqyd  t3_hfmqyd          1978   
4  1.594671e+09  hqmot1  t3_hqmot1          2893   

                                                 url  total_awards_received  \
0  https://www.reddit.com/r/LifeProTips/comments/...                     37   
1  https://www.reddit.com/r/LifeProTips/comments/...                     13   
2  https://www.reddit.com/r/LifeProTips/comments/...                     23   
3  https://www.reddit.com/r/LifeProTips/comments/...                     20   
4  https://www.reddit.com/r/LifeProTips/comments/...                     45   

               author  
0               w2555  
1       Moonripple616  
2      ninnymugginsss  
3            podotash  
4  WellThatsPrompting

In [22]:
df[df.duplicated(subset='title')]

subreddit                                           selftext  score  \
593  LifeProTips  Here is a list of sites for online work that a...   6620   
733  LifeProTips  Edit: Wow 2 silver! My first time, thanks kind...   3627   

                                                 title  upvote_ratio  \
593  LPT: If you have a lot of free time at the mom...          0.96   
733  LPT If you ever forget your WiFi password or y...          0.96   

      created_utc      id   fullname  num_comments  \
593  1.588112e+09  g9wyby  t3_g9wyby           291   
733  1.575529e+09  e6dlbm  t3_e6dlbm           270   

                                                   url  total_awards_received  \
593  https://www.reddit.com/r/LifeProTips/comments/...                      3   
733  https://www.reddit.com/r/LifeProTips/comments/...                      2   

        author  
593  IveyRoney  
733   slackftw

In [27]:
df.iloc[593]['title']

"LPT: If you have a lot of free time at the moment, you can generate a little income on the side by doing online work like teaching english, transcription, microtasks or surveys. It's not a fortune but if you have time to spare anyway it's a good way to pay a few bills. (list of sites attached)"

In [28]:
df.loc[df['title'] == "LPT: If you have a lot of free time at the moment, you can generate a little income on the side by doing online work like teaching english, transcription, microtasks or surveys. It's not a fortune but if you have time to spare anyway it's a good way to pay a few bills. (list of sites attached)",:]

subreddit                                           selftext  score  \
557  LifeProTips  Here is a list of sites for online work that a...   8053   
593  LifeProTips  Here is a list of sites for online work that a...   6620   

                                                 title  upvote_ratio  \
557  LPT: If you have a lot of free time at the mom...          0.95   
593  LPT: If you have a lot of free time at the mom...          0.96   

      created_utc      id   fullname  num_comments  \
557  1.592401e+09  har8qo  t3_har8qo           337   
593  1.588112e+09  g9wyby  t3_g9wyby           291   

                                                   url  total_awards_received  \
557  https://www.reddit.com/r/LifeProTips/comments/...                      5   
593  https://www.reddit.com/r/LifeProTips/comments/...                      3   

        author  
557   IvyRoney  
593  IveyRoney

In [29]:
df.iloc[733]['title']

'LPT If you ever forget your WiFi password or you want to get your school WiFi password etc. Just type this command into the command line of a computer already connected to that WiFi: netsh wlan show profile WiFi-name key=clear'

In [30]:
df.loc[df['title'] == "LPT If you ever forget your WiFi password or you want to get your school WiFi password etc. Just type this command into the command line of a computer already connected to that WiFi: netsh wlan show profile WiFi-name key=clear",:]


subreddit                                           selftext  score  \
7    LifeProTips                                                     97685   
733  LifeProTips  Edit: Wow 2 silver! My first time, thanks kind...   3627   

                                                 title  upvote_ratio  \
7    LPT If you ever forget your WiFi password or y...          0.95   
733  LPT If you ever forget your WiFi password or y...          0.96   

      created_utc      id   fullname  num_comments  \
7    1.568801e+09  d5vknk  t3_d5vknk          2908   
733  1.575529e+09  e6dlbm  t3_e6dlbm           270   

                                                   url  total_awards_received  \
7    https://www.reddit.com/r/LifeProTips/comments/...                     13   
733  https://www.reddit.com/r/LifeProTips/comments/...                      2   

       author  
7        None  
733  slackftw

Based on the above, it looks like two of the posts were duplicates where another user copied a previous post. Since we don't need both instances of the post, we can drop the duplicated posts (index 593 and 733).

In [31]:
df = df.drop([593,733],axis=0)
df = df.reset_index()

In [23]:
#df.to_csv('postlistlpt.csv')

In [35]:
df[df.duplicated(subset='selftext') & (df['selftext'] != "")]

index    subreddit   selftext  score  \
935    937  LifeProTips  [removed]   1712   

                                                 title  upvote_ratio  \
935  LPT: Preheat your Thermos by filling it with s...          0.93   

      created_utc      id   fullname  num_comments  \
935  1.593794e+09  hkmaj2  t3_hkmaj2           168   

                                                   url  total_awards_received  \
935  https://www.reddit.com/r/LifeProTips/comments/...                      0   

                author  
935  frizzycornerstone

There are no duplicated selftext values except for blank values and 'removed', so we can leave it. 

_Repeat for UnethicalLifeProTips_

In [38]:
sreddit_ulpt = reddit.subreddit('UnethicalLifeProTips')
ulpt_hot_1000 = sreddit_ulpt.top('year',limit=1000)

In [39]:
post_list = []

for p in ulpt_hot_1000:
    post={}
    post['subreddit'] = str(p.subreddit)
    post['selftext'] = str(p.selftext)
    post['score'] = p.score
    post['title'] = str(p.title)
    post['upvote_ratio'] = p.upvote_ratio
    post['created_utc'] = p.created_utc
    post['id'] = str(p.id)
    post['fullname'] = str(p.fullname)
    post['num_comments'] = p.num_comments
    post['url'] = str(p.url)
    post['total_awards_received'] = p.total_awards_received
    post['author'] = p.author
    post_list.append(post)

In [40]:
df_ulpt = pd.DataFrame(post_list)

In [41]:
df_ulpt.head()

subreddit                                           selftext  \
0  UnethicalLifeProTips                                                      
1  UnethicalLifeProTips  This is a repost from last year but the holida...   
2  UnethicalLifeProTips  Military girlfriends/wives are FREEEEAKKKKS. A...   
3  UnethicalLifeProTips                                                      
4  UnethicalLifeProTips  I found this out because it actually was true ...   

   score                                              title  upvote_ratio  \
0  59286  ULPT: if you’re stuck on an annoying call, put...          0.93   
1  56794  ULPT: If a relative keeps asking you about hav...          0.93   
2  42918  ULPT: If you live near a US military base, it'...          0.83   
3  38976  ULPT: When you give someone a gift card as a g...          0.94   
4  38160  ULPT: If you have a significant unexplained em...          0.95   

    created_utc      id   fullname  num_comments  \
0  1.595948e+09  hzg6il  t3_hzg6il           844   
1  1.568487e+09  d49942  t3_d49942           916   
2  1.578488e+09  els8pu  t3_els8pu          2933   
3  1.593633e+09  hjhpl0  t3_hjhpl0           859   
4  1.568736e+09  d5ixhz  t3_d5ixhz          1078   

                                                 url  total_awards_received  \
0  https://www.reddit.com/r/UnethicalLifeProTips/...                      8   
1  https://www.reddit.com/r/UnethicalLifeProTips/...                      2   
2  https://www.reddit.com/r/UnethicalLifeProTips/...                      4   
3  https://www.reddit.com/r/UnethicalLifeProTips/...                      1   
4  https://www.reddit.com/r/UnethicalLifeProTips/...                      2   

             author  
0        gotBooched  
1     FascinatedBox  
2  BidensBuddyStrom  
3        d3vourm3nt  
4       squirrelbee

In [42]:
df_ulpt[df_ulpt.duplicated(subset='title')]

subreddit                                           selftext  \
972  UnethicalLifeProTips  How do I verify myself in a NSFW discord serve...   

     score         title  upvote_ratio   created_utc      id   fullname  \
972      0  ULPT REQUEST          0.41  1.572581e+09  dpz64y  t3_dpz64y   

     num_comments                                                url  \
972            15  https://www.reddit.com/r/UnethicalLifeProTips/...   

     total_awards_received          author  
972                      0  JacksonTheRock

In [45]:
df_ulpt[df_ulpt.duplicated(subset='selftext') & (df_ulpt['selftext'] != "")]

Empty DataFrame
Columns: [subreddit, selftext, score, title, upvote_ratio, created_utc, id, fullname, num_comments, url, total_awards_received, author]
Index: []

There are no duplicated posts that we need to address in this dataframe.

In [47]:
master_df = df.append(df_ulpt)

In [50]:
master_df = master_df.drop(columns='index')

In [51]:
master_df.to_csv('combined_top.csv',index=False)